### ISSUE TITLE
Crosshair issue

### ISSUE THREAD

**Issue by hardbassblyat** [CriticalFlaw/FlawHUD.Installer#2] opened 2020-05-13 20:31 UTC
Upon changing the Y axis, the hud's crosshair will no longer appear in game.

**Comment by CriticalFlaw** [comment] 2020-05-26 00:15
Could you post a screenshot of your installer settings?

**Comment by CriticalFlaw** [comment] 2020-06-07 17:48
Closing due to not being able to reproduce the bug and the user has no responded.

**Closed by CriticalFlaw** 2020-06-07 17:48 UTC
Labels: invalid
