### ISSUE TITLE
Health panel 

### ISSUE THREAD

**Issue by memes-ui** [CriticalFlaw/FlawHUD.Installer#3] opened 2020-05-22 22:52 UTC
I want to have the health panel, but it's not working. When i open the game It shows it as the default health cross.

**Comment by CriticalFlaw** [comment] 2020-05-26 00:00
Currently the 'health cross' is a rectangular panel behind the health value, changing color when low or buffed. There is an option to have the health value be colored instead of the background, is that the feature you're having trouble with? Could you be more specific as to which health panel you're expecting to see?

**Comment by CriticalFlaw** [comment] 2020-06-07 17:49
Closing due to not being able to reproduce the bug and the user has no responded.

**Closed by CriticalFlaw** 2020-06-07 17:49 UTC
Labels: invalid
